config/routes.rb
RailsBlog::Application.routes.draw do
  get "users/new"
  root 'posts#index'
  resources :posts

  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :users
  resources :sessions
  resources :shared_posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_one :shared_post

end

app/models/shared_post.rb
class SharedPost < ActiveRecord::Base
  belongs_to :post

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :email, :password, :password_confirmation

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :shared_user

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to log_in_path, alert: "Not authorized" if current_user.nil?
    end

    def shared_user
      if @current_user.role == 'shared'
        redirect_to root_path, :notice => "Unautherised Access!!"
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authorize, except: [:index]

  before_filter :shared_user, except: [:index, :show]

  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # http_basic_authenticate_with name: "admin", password: "password", except: [ :show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if current_user.role == 'shared'
      if @post.shared_post.try(:users)
        redirect_to root_path, :notice => "Unautherised Access!!" unless @post.shared_post.try(:users).split(',').include? current_user
      end
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :password, :users)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/shared_posts_controller.rb
class SharedPostsController < ApplicationController
  before_action :authorize, :shared_user

  def index

  end

  def show
    @sharedPost = SharedPost.find_by_post_id(params[:id])

    if !@sharedPost
      @sharedPost = SharedPost.new
      @sharedPost.post_id = params[:id]
    end
  end

  def create
    @sharedPost = SharedPost.new(shared_post_params)

    respond_to do |format|
      if @sharedPost.save
        create_shared_users(shared_post_params)

        format.html { redirect_to root_url, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

   def update
    @sharedPost = SharedPost.find(params[:id])

    respond_to do |format|
      if @sharedPost.update(shared_post_params)
        create_shared_users(shared_post_params)

        format.html { redirect_to root_url, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @sharedPost.errors, status: :unprocessable_entity }
      end
    end
  end

  private
   def shared_post_params
      params.require(:shared_post).permit(:post_id,:password, :users, :id)
   end

   def create_shared_users(shared_post_params)
      users = shared_post_params[:users]

      users.split(',').each do |user|
        find_user = User.find_by_email(user.strip)

        unless find_user
          shared_user = User.new(email: user.strip, password: shared_post_params[:password], role: 'shared')
          shared_user.save
        else
          # find_user.update()
        end
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed up!"
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shared_posts_helper.rb
module SharedPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="user_nav">
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log out", log_out_path %>
    <% else %>
      <%= link_to "Sign up", sign_up_path %> or
      <%= link_to "log in", log_in_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div style="width:550px;">
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div style="width:700px; margin:20px;">

<h1>Listing posts</h1>


<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Share', shared_post_path(post) %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>Blog : <%= @post.title %></h1>

<div style="width:700px; margin:20px;">
  <table class="table table-striped table-bordered">
    <tr>
      <td width="150">
        <strong>Title:</strong>
      </td>
      <td>
        <%= @post.title %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Body:</strong>
      </td>
      <td>
        <%= @post.body %>
      </td>
    </tr>
  </table>
</div>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared_posts/_form.html.erb
<%= form_for(@sharedPost) do |f| %>

  <div class="share_blog_content">
    <div class="field">
      <%= f.label :post_id %><br>
      <%= @sharedPost.post_id %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.text_field :password %>
    </div>
    <div class="field">
      <%= f.label :users %><br>
      <%= f.text_area :users %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/shared_posts/show.html.erb
<h1>Share Blog: </h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/users/new.html.haml
%h1 Users#new
%p Find me in app/views/users/new.html.haml